//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineJewelryShoppingMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogMst
    {
        public int blogId { get; set; }
        public string blogImg { get; set; }
        public string blogTitle { get; set; }
        public string blogContent { get; set; }
        public System.DateTime cdate { get; set; }
    }
}
