//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineJewelryShoppingMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentMst
    {
        public int cmtId { get; set; }
        public int userId { get; set; }
        public string itemCode { get; set; }
        public string cmtContent { get; set; }
        public decimal ratingValue { get; set; }
    
        public virtual ItemMst ItemMst { get; set; }
        public virtual UserRegMst UserRegMst { get; set; }
    }
}
