//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineJewelryShoppingMVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DimInfoMst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimInfoMst()
        {
            this.ItemMsts = new HashSet<ItemMst>();
        }
    
        public string dimId { get; set; }
        public string dimShape { get; set; }
        public decimal dimCrt { get; set; }
        public decimal dimSize { get; set; }
        public string dimColor { get; set; }
        public string dimClarity { get; set; }
        public string dimCut { get; set; }
        public string dimPolish { get; set; }
        public string dimSymmetry { get; set; }
        public string dimReport { get; set; }
        [DataType(DataType.Currency)]
        public decimal dimRate { get; set; }
        public string dimImg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemMst> ItemMsts { get; set; }
    }
}
