//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineJewelryShoppingMVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class StoneInfoMst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StoneInfoMst()
        {
            this.ItemMsts = new HashSet<ItemMst>();
        }

        [Required]
        public string stoneId { get; set; }
        [Required]
        public string stoneShape { get; set; }
        [Required]
        [DisplayName("Stone Criteria")]
        [Range(0.1, 1, ErrorMessage = "Criteria must be from 0.1 to 1 ")]
        public decimal stoneCrt { get; set; }
        [Required]
        public string stoneColor { get; set; }
        [Required]
        [DisplayName("Stone Rate")]
        [Range(1, 100000000, ErrorMessage = "Rate must be from 1 to 100,000,000 ")]
        public decimal stoneRate { get; set; }
        public string stoneImg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemMst> ItemMsts { get; set; }
    }
}
