//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineJewelryShoppingMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionMst
    {
        public string transactionId { get; set; }
        public string userId { get; set; }
        public string guestId { get; set; }
        public string itemCode { get; set; }
        public int qty { get; set; }
        public decimal total { get; set; }
        public string approvalStt { get; set; }
    
        public virtual GuestMst GuestMst { get; set; }
        public virtual ItemMst ItemMst { get; set; }
        public virtual UserRegMst UserRegMst { get; set; }
    }
}
